---

- name: Some Java Application
  hosts: all
  become: yes
  
  tasks:    
    - name: Delete a directory if it exists
      file:
        path: /home/mftiedu/khannanova-dr-3
        state: absent
  
    - name: Creating directory
      file:
        path: /home/mftiedu/khannanova-dr-3
        state: directory
        mode: '0777'
    
    - name: Copying Jar
      copy:
        src: ./target/jenkins-1.0-SNAPSHOT.jar
        dest: /home/mftiedu/khannanova-dr-3       
    
    - name: Deploying Jar
      shell: cd /home/mftiedu/khannanova-dr-3 && java -jar jenkins-1.0-SNAPSHOT.jar 
        
...
