---
- name: install app
  hosts: all
  become: yes
  
  tasks:
    - name: system os detection 
      debug: var=ansible_os_family
      
    - name: gather package info
      package_facts:
      
    - block: # install python on centos
      - name: install python
        yum: update_cache=yes name=python3 state=latest
        when: "'python3' not in ansible_facts.packages"
      - name: install pip
        yum: update_cache=yes name=python3-pip state=latest
        when: "'python3-pip' not in ansible_facts.packages"
      when: ansible_os_family == "RedHat"
      
    - block: # install python on debian
      - name: install python
        apt: update_cache=yes name=python3 state=latest
        when: "'python3' not in ansible_facts.packages"
      - name: install pip
        apt: update_cache=yes name=python3-pip state=latest
        when: "'python3-pip' not in ansible_facts.packages"
      when: ansible_os_family == "Debian"
      
    - block: # install requirements
      - name: install argparse
        pip: executable=pip3 name=argparse state=latest
        
    - name: delete a directory if it exists
      file:
        path: '{{proj_dir}}'
        state: absent 

    - name: create a directory
      file:
        path: '{{proj_dir}}'
        state: directory
        mode: '1777'
        
    - name: download app
      git:
        repo: '{{git_proj_link}}'
        dest: '{{proj_dir}}'
...
